global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: payments
    static_configs:
      - targets: ['payments-api:8080']
  - job_name: taxi
    static_configs:
      - targets: ['taxi-api:8081']
  - job_name: bus
    static_configs:
      - targets: ['bus-api:8082']
  - job_name: commerce
    static_configs:
      - targets: ['commerce-api:8083']
  - job_name: utilities
    static_configs:
      - targets: ['utilities-api:8084']
  - job_name: freight
    static_configs:
      - targets: ['freight-api:8085']
  - job_name: carmarket
    static_configs:
      - targets: ['carmarket-api:8086']
  - job_name: jobs
    static_configs:
      - targets: ['jobs-api:8087']
  - job_name: stays
    static_configs:
      - targets: ['stays-api:8088']
  - job_name: doctors
    static_configs:
      - targets: ['doctors-api:8089']
  - job_name: food
    static_configs:
      - targets: ['food-api:8090']
  - job_name: chat
    static_configs:
      - targets: ['chat-api:8091']

  - job_name: flights
    static_configs:
      - targets: ['flights-api:8092']

  - job_name: ai_gateway
    static_configs:
      - targets: ['ai-gateway:8099']

  - job_name: agriculture
    static_configs:
      - targets: ['agriculture-api:8093']

  - job_name: carrental
    static_configs:
      - targets: ['carrental-api:8095']

  - job_name: livestock
    static_configs:
      - targets: ['livestock-api:8094']

  - job_name: realestate
    static_configs:
      - targets: ['realestate-api:8092']
  - job_name: parking_onstreet
    static_configs:
      - targets: ['parking-onstreet-api:8096']
  - job_name: parking_offstreet
    static_configs:
      - targets: ['parking-offstreet-api:8097']

  # Blackbox HTTPS probes for public endpoints (via blackbox-exporter)
  - job_name: blackbox_https
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://payments.syriasuperapp.com
        - https://taxi.syriasuperapp.com
        - https://grafana.syriasuperapp.com
        - https://automarket.syriasuperapp.com
        - https://bus.syriasuperapp.com
        - https://chat.syriasuperapp.com
        - https://commerce.syriasuperapp.com
        - https://doctors.syriasuperapp.com
        - https://food.syriasuperapp.com
        - https://freight.syriasuperapp.com
        - https://jobs.syriasuperapp.com
        - https://stays.syriasuperapp.com
        - https://utilities.syriasuperapp.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: postgres-payments
    static_configs:
      - targets: ['pg-payments-exporter:9187']
