services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bus
    ports:
      - "5435:5432"
    volumes:
      - bus_db_data:/var/lib/postgresql/data

  api:
    container_name: bus-api
    build:
      context: ../..
      dockerfile: apps/bus/Dockerfile
    env_file:
      - .env
    environment:
      JWT_JWKS_URL: ${JWT_JWKS_URL:-http://host.docker.internal:8080/.well-known/jwks.json}
    ports:
      - "8082:8082"
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.bus.rule=Host(`bus.${BASE_DOMAIN}`)"
      - "traefik.http.routers.bus.entrypoints=websecure"
      - "traefik.http.routers.bus.tls.certresolver=letsencrypt"
      - "traefik.http.services.bus.loadbalancer.server.port=8082"
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "uvicorn app.main:app --host ${APP_HOST:-0.0.0.0} --port ${APP_PORT:-8082} --reload"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"

volumes:
  bus_db_data:
networks:
  web:
    external: true
    name: web
  internal:
    external: true
    name: internal
