name: shared_core
description: Core networking, config, observability, and security utilities for Syria Super-App clients
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  connectivity_plus: ^6.0.3
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  sentry_flutter: ^8.7.0
  retry: ^3.1.1
  meta: ^1.11.0
  collection: ^1.18.0
  shared_ui:
    path: ../shared_ui
dependency_overrides:
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false
