name: payments_flutter
description: MVP client for the Payments API (Syria Super-App)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  go_router: ^14.2.7
  shared_preferences: ^2.2.3
  uuid: ^4.5.1
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  share_plus: ^9.0.0
  intl: ^0.19.0
  local_auth: ^2.3.0
  crypto: ^3.0.3
  uni_links: ^0.5.1
  connectivity_plus: ^6.1.0
  sentry_flutter: ^8.6.0
  flutter_secure_storage: ^9.2.2
  flutter_windowmanager: ^0.2.0
  flutter_jailbreak_detection: ^1.10.0
  path_provider: ^2.1.4
  shared_ui:
    path: ../shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
