services:
  api:
    env_file: []
    volumes:
      - ./app:/app/app:ro
      - ./tests:/app/apps/freight/tests:ro
      - ../../libs:/app/libs:ro
      - ../../libs/superapp_shared/superapp_shared:/app/superapp_shared:ro
    environment:
      PYTHONUNBUFFERED: "1"
      UVICORN_WORKERS: "1"
      UVICORN_LOG_LEVEL: "warning"
      DB_URL: postgresql+psycopg2://postgres:postgres@db:5432/freight
      PYTHONPATH: /app/libs:/app
    mem_limit: "2g"
    networks:
      - default

