services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food
    ports:
      - "5544:5432"
    volumes:
      - food_courier_db_data:/var/lib/postgresql/data

  api:
    build:
      context: ../..
      dockerfile: operators/food_courier/Dockerfile
    env_file:
      - ../../apps/food/.env
    environment:
      PYTHONPATH: /app
    ports:
      - "8092:8092"
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "uvicorn operators.food_courier.main:app --host ${APP_HOST:-0.0.0.0} --port ${APP_PORT:-8092} --reload"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    ports:
      - "6392:6379"

volumes:
  food_courier_db_data:
