"""cash_requests

Revision ID: 71eba1297e5d
Revises: 12ca0e4c2fd7
Create Date: 2025-09-28 20:08:01.484954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71eba1297e5d'
down_revision: Union[str, None] = '12ca0e4c2fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_user_id', sa.UUID(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add is_agent with default false for existing rows, then drop default
    op.add_column('users', sa.Column('is_agent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.execute("UPDATE users SET is_agent = false WHERE is_agent IS NULL")
    op.alter_column('users', 'is_agent', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_agent')
    op.drop_table('cash_requests')
    # ### end Alembic commands ###
