services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taxi
    ports:
      - "5534:5432"
    volumes:
      - taxi_driver_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ../..
      dockerfile: operators/taxi_driver/Dockerfile
    env_file:
      - ../../apps/taxi/.env
    environment:
      # Ensure imports of Taxi domain code work
      PYTHONPATH: /app
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["sh", "-c", "alembic upgrade head && uvicorn operators.taxi_driver.main:app --host ${APP_HOST:-0.0.0.0} --port ${APP_PORT:-8083} --reload"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    ports:
      - "6383:6379"

  migrate:
    build:
      context: ../..
      dockerfile: operators/taxi_driver/Dockerfile
    env_file:
      - ../../apps/taxi/.env
    environment:
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "alembic upgrade head"]
    profiles: ["migrate"]

volumes:
  taxi_driver_db_data:
