name: taxi_driver_flutter
description: Standalone Driver UI for the Taxi service (reusing taxi_flutter code)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  shared_ui:
    path: ../shared_ui
  http: ^1.2.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  flutter_map: ^7.0.2
  maplibre_gl: ^0.21.0
  latlong2: ^0.9.1
  web_socket_channel: ^2.4.0
  geolocator: ^11.1.0
  flutter_foreground_task: ^6.3.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.2.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  mobile_scanner: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env

dependency_overrides:
  maplibre_gl: ^0.21.0
