services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carmarket
    ports:
      - "5439:5432"
    volumes:
      - carmarket_db_data:/var/lib/postgresql/data

  api:
    container_name: carmarket-api
    build:
      context: ../..
      dockerfile: apps/carmarket/Dockerfile
    env_file:
      - .env
    environment:
      JWT_JWKS_URL: ${JWT_JWKS_URL:-http://host.docker.internal:8080/.well-known/jwks.json}
    ports:
      - "8086:8086"
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.carmarket.rule=Host(`carmarket.${BASE_DOMAIN}`)"
      - "traefik.http.routers.carmarket.entrypoints=websecure"
      - "traefik.http.routers.carmarket.tls.certresolver=letsencrypt"
      - "traefik.http.services.carmarket.loadbalancer.server.port=8086"
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "uvicorn app.main:app --host ${APP_HOST:-0.0.0.0} --port ${APP_PORT:-8086} --reload"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    ports:
      - "6385:6379"

volumes:
  carmarket_db_data:
networks:
  web:
    external: true
    name: web
  internal:
    external: true
    name: internal
