name: bus_operator_portal
description: Minimal portal for bus operators (Super‑App demo)
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  mobile_scanner: ^5.0.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
