services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flights
    ports:
      - "5445:5432"
    volumes:
      - flights_db_data:/var/lib/postgresql/data

  api:
    container_name: flights-api
    build:
      context: ../..
      dockerfile: apps/flights/Dockerfile
    env_file:
      - .env
    environment:
      JWT_JWKS_URL: ${JWT_JWKS_URL:-http://host.docker.internal:8080/.well-known/jwks.json}
    ports:
      - "8092:8092"
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.flights.rule=Host(`flights.${BASE_DOMAIN}`)"
      - "traefik.http.routers.flights.entrypoints=websecure"
      - "traefik.http.routers.flights.tls.certresolver=letsencrypt"
      - "traefik.http.services.flights.loadbalancer.server.port=8092"
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "uvicorn app.main:app --host ${APP_HOST:-0.0.0.0} --port ${APP_PORT:-8092} --reload"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    ports:
      - "6391:6379"

volumes:
  flights_db_data:
networks:
  web:
    external: true
    name: web
  internal:
    external: true
    name: internal
