name: flights_flutter
description: MVP client for the Flights API (Syria Super-App)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  shared_ui:
    path: ../shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
