version: '3.9'

networks:
  web:
    external: true
    name: web
  internal:
    external: true
    name: internal

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus:ro
    depends_on:
      - blackbox
    networks:
      - internal
  grafana:
    image: grafana/grafana-oss:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${BASE_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.routers.grafana.middlewares=secure-headers@docker,grafana-basic@docker"
      - "traefik.http.middlewares.grafana-basic.basicauth.users=${GRAFANA_BASIC_AUTH_USERS}"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - web
  alertmanager:
    image: prom/alertmanager:latest
    environment:
      - SLACK_WEBHOOK_URL
      - SLACK_CHANNEL
      - ALERT_EMAIL_TO
      - ALERT_EMAIL_FROM
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASS
    volumes:
      - ./alertmanager:/etc/alertmanager:ro
    networks:
      - internal
  blackbox:
    image: prom/blackbox-exporter:latest
    networks:
      - internal
  node-exporter:
    image: prom/node-exporter:latest
    command:
      - --path.rootfs=/host
      - --path.sysfs=/host/sys
      - --path.procfs=/host/proc
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    networks:
      - internal
    restart: unless-stopped
  pg-payments-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@payments-db:5432/payments?sslmode=disable
    networks:
      - internal
    restart: unless-stopped
