name: taxi_flutter
description: MVP client for the Taxi API
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  uuid: ^4.5.1
  flutter_map: ^7.0.2
  maplibre_gl: ^0.24.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  web_socket_channel: ^2.4.0
  # Removed driver-only deps from rider app
  flutter_local_notifications: ^17.2.1
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  flutter_contacts: ^1.1.7
  local_auth: ^2.3.0
  shared_ui:
    path: ../shared_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
  generate: true
