services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: utilities
    volumes:
      - utilities_db_data:/var/lib/postgresql/data

  api:
    container_name: utilities-api
    build:
      context: ../..
      dockerfile: apps/utilities/Dockerfile
    env_file:
      - .env
    ports:
      - "8084:8084"
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.utilities.rule=Host(`utilities.${BASE_DOMAIN}`)"
      - "traefik.http.routers.utilities.entrypoints=websecure"
      - "traefik.http.routers.utilities.tls.certresolver=letsencrypt"
      - "traefik.http.services.utilities.loadbalancer.server.port=8084"
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "uvicorn app.main:app --host ${APP_HOST:-0.0.0.0} --port ${APP_PORT:-8084} --reload"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7-alpine
    ports:
      - "6383:6379"

volumes:
  utilities_db_data:
networks:
  web:
    external: true
    name: web
  internal:
    external: true
    name: internal
