name: Bandit Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  bandit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml]
      - name: Run bandit (apps + libs)
        run: |
          bandit -r syria-superapp/apps -x "**/tests/**" || true
          bandit -r syria-superapp/libs -x "**/tests/**" || true

