name: Docker Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag"
        required: false
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [payments, taxi, bus, flights, commerce, utilities, freight, automarket, jobs, stays, doctors, food, chat]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Compute tag
        id: vars
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi
      - name: Build and push ${{ matrix.app }}
        uses: docker/build-push-action@v6
        with:
          # Use repo root as build context since Dockerfiles copy from apps/* and libs/*
          context: .
          file: apps/${{ matrix.app }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ format('docker.io/{0}/syria-{1}:{2}', secrets.DOCKERHUB_USERNAME, matrix.app, steps.vars.outputs.tag) }}
            ${{ format('docker.io/{0}/syria-{1}:latest', secrets.DOCKERHUB_USERNAME, matrix.app) }}
