name: Python Dependency Audit

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
      - name: Audit each requirements.txt in apps
        run: |
          set -e
          for f in $(find syria-superapp/apps -maxdepth 2 -name requirements.txt); do
            echo "[audit] $f"
            pip-audit -r "$f" || true
          done

