name: Smoke Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        app: [payments, food]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run smoke for ${{ matrix.app }}
        env:
          APPS: ${{ matrix.app }}
        run: |
          bash tools/smoke/run_ci_smoke.sh
