name: Weekly Prod Audit

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  prod-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run static prod audit
        run: |
          set -e
          python3 tools/prod_audit.py | tee prod_audit.log

      - name: Upload audit log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: prod-audit-log
          path: prod_audit.log

      - name: Open issue on findings
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('prod_audit.log', 'utf8');
            const title = `Prod audit detected issues (${new Date().toISOString()})`;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body
            });

